wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705568370.482351
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.9.16
      5: 0.15.12
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
