wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705572809.472367
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.9.16
      5: 0.15.12
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
pretrained_model_name_or_path:
  desc: null
  value: timbrooks/instruct-pix2pix
revision:
  desc: null
  value: null
dataset_name:
  desc: null
  value: annyorange/Text-style-dataset
dataset_config_name:
  desc: null
  value: null
train_data_dir:
  desc: null
  value: null
init_image_column:
  desc: null
  value: init_image
edited_image_column:
  desc: null
  value: style_image
edit_prompt_column:
  desc: null
  value: edit_prompt
val_image_url:
  desc: null
  value: https://github.com/AnnyOrange/picture/blob/main/init.png?raw=true
val_gt_url:
  desc: null
  value: https://github.com/AnnyOrange/picture/blob/main/style.png?raw=true
validation_prompt:
  desc: null
  value: Transform the text in the image into Anny's style with a white background.
num_validation_images:
  desc: null
  value: 1
validation_epochs:
  desc: null
  value: 1
max_train_samples:
  desc: null
  value: 11
output_dir:
  desc: null
  value: text-finetuned
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: 42
resolution:
  desc: null
  value: 256
center_crop:
  desc: null
  value: false
random_flip:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 2
val_batch_size:
  desc: null
  value: 4
num_train_epochs:
  desc: null
  value: 100
max_train_steps:
  desc: null
  value: 200
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 5.0e-06
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
conditioning_dropout_prob:
  desc: null
  value: null
use_8bit_adam:
  desc: null
  value: false
allow_tf32:
  desc: null
  value: false
use_ema:
  desc: null
  value: true
non_ema_revision:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: true
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: fp16
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 300
checkpoints_total_limit:
  desc: null
  value: 2
resume_from_checkpoint:
  desc: null
  value: null
enable_xformers_memory_efficient_attention:
  desc: null
  value: true
